export const ROLES = {
  ADMIN: 'ADMIN',
  AGENT: 'AGENT',
  PARTNER: 'PARTNER',
  APPLICANT: 'APPLICANT'
} as const;

export const PERMISSIONS = [
  'USER_MANAGE',
  'RBAC_MANAGE',
  'AUDIT_VIEW',

  'APPLICANT_PROFILE_VIEW',
  'APPLICANT_PROFILE_UPDATE',
  'APPLICANT_PROFILE_VERIFY',

  'JOB_MANAGE',
  'JOB_VIEW',

  'APPLICATION_MANAGE',
  'APPLICATION_VIEW_SELF',

  'REPORT_VIEW',
  'SYSTEM_CONFIG_MANAGE'
] as const;

export const ROLE_PERMISSIONS: Record<string, string[]> = {
  [ROLES.ADMIN]: [
    ...PERMISSIONS
  ],
  [ROLES.AGENT]: [
    'APPLICANT_PROFILE_VIEW',
    'APPLICANT_PROFILE_UPDATE',
    'APPLICANT_PROFILE_VERIFY',
    'JOB_MANAGE',
    'APPLICATION_MANAGE',
    'REPORT_VIEW'
  ],
  [ROLES.PARTNER]: [
    'APPLICANT_PROFILE_VIEW',
    'JOB_VIEW',
    'APPLICATION_MANAGE',
    'REPORT_VIEW'
  ],
  [ROLES.APPLICANT]: [
    'APPLICATION_VIEW_SELF',
    'APPLICANT_PROFILE_UPDATE'
  ]
};
