export const ROLES = {
  APPLICANT: 'APPLICANT',
  LOCAL_AGENCY: 'LOCAL_AGENCY',
  MUB_STAFF: 'MUB_STAFF',
  MUB_ADMIN: 'MUB_ADMIN',
  PARTNER_EMPLOYER: 'PARTNER_EMPLOYER',
  FINANCE_OFFICER: 'FINANCE_OFFICER'
} as const;

export const PERMISSIONS = [
  'USER_SELF_REGISTER',
  'USER_READ',
  'USER_CREATE',
  'USER_UPDATE',
  'USER_SUSPEND',
  'USER_REACTIVATE',
  'USER_APPROVE',
  'USER_REJECT',


  'RBAC_MANAGE',

  'AUDIT_VIEW',

  'APPLICANT_SELF_VIEW',
  'APPLICANT_SELF_UPDATE',
  'APPLICANT_SELF_DOCUMENT_UPLOAD',
  'APPLICANT_SELF_STATUS_TRACK',

  'APPLICANT_VIEW',
  'APPLICANT_CREATE',
  'APPLICANT_UPDATE',
  'APPLICANT_DOCUMENT_UPLOAD',
  'APPLICANT_DOCUMENT_VERIFY',

  'SKILL_VIEW',
  'SKILL_CREATE',
  'SKILL_UPDATE',

  'LOCAL_AGENCY_SELF_REGISTER',
  'LOCAL_AGENCY_SELF_VIEW',
  'LOCAL_AGENCY_SELF_UPDATE',

  'LOCAL_AGENCY_VIEW',
  'LOCAL_AGENCY_MANAGE',
  'LOCAL_AGENCY_APPROVE',
  'LOCAL_AGENCY_SUSPEND',
  'LOCAL_AGENCY_REACTIVATE',

  'EMPLOYER_SELF_REGISTER',
  'EMPLOYER_SELF_VIEW',
  'EMPLOYER_SELF_UPDATE',

  'EMPLOYER_VIEW',
  'EMPLOYER_MANAGE',
  'EMPLOYER_APPROVE',
  'EMPLOYER_SUSPEND',
  'EMPLOYER_REACTIVATE',

  'JOB_CREATE',
  'JOB_UPDATE',
  'JOB_PUBLISH',
  'JOB_MANAGE',
  'JOB_VIEW',

  'MATCHING_VIEW',
  'MATCHING_MANAGE',

  'APPLICATION_VIEW_SELF',
  'APPLICATION_CREATE_SELF',
  'APPLICATION_VIEW',
  'APPLICATION_CREATE',
  'APPLICATION_MANAGE',

  'MEDICAL_VIEW',
  'MEDICAL_UPLOAD_RESULT',
  'MEDICAL_UPDATE_CLEARANCE',
  'MEDICAL_ATTACH_REPORT',

  'VISA_VIEW_SELF',
  'VISA_VIEW',
  'VISA_CREATE',
  'VISA_UPDATE',
  'VISA_SUBMIT',

  'APPLICANT_EXPENSE_TYPE_MANAGE',
  'APPLICANT_EXPENSE_MANAGE',
  'COMPANY_EXPENSE_TYPE_MANAGE',
  'COMPANY_EXPENSE_MANAGE',

  'REPORT_VIEW',
  'REPORT_ANALYTICS_VIEW',

] as const;

export type RoleCode = (typeof ROLES)[keyof typeof ROLES];
export type PermissionCode = (typeof PERMISSIONS)[number];

export const ROLE_PERMISSIONS: Record<RoleCode, readonly PermissionCode[]> = {
  [ROLES.MUB_ADMIN]: [...PERMISSIONS],

  [ROLES.MUB_STAFF]: [
    'USER_READ',

    'APPLICANT_VIEW',
    'APPLICANT_CREATE',
    'APPLICANT_UPDATE',
    'APPLICANT_DOCUMENT_UPLOAD',
    'APPLICANT_DOCUMENT_VERIFY',

    'SKILL_VIEW',
    'SKILL_CREATE',
    'SKILL_UPDATE',

    'LOCAL_AGENCY_VIEW',
    'EMPLOYER_VIEW',
    'JOB_VIEW',

    'MATCHING_VIEW',
    'MATCHING_MANAGE',

    'APPLICATION_VIEW',
    'APPLICATION_CREATE',
    'APPLICATION_MANAGE',

  

    'MEDICAL_VIEW',
    'MEDICAL_UPLOAD_RESULT',
    'MEDICAL_UPDATE_CLEARANCE',
    'MEDICAL_ATTACH_REPORT',

    'VISA_VIEW',
    'VISA_CREATE',
    'VISA_UPDATE',
    'VISA_SUBMIT',



    'REPORT_VIEW',
  ],

  [ROLES.LOCAL_AGENCY]: [
    'LOCAL_AGENCY_SELF_REGISTER',
    'LOCAL_AGENCY_SELF_VIEW',
    'LOCAL_AGENCY_SELF_UPDATE',

    'APPLICANT_CREATE',
    'APPLICANT_UPDATE',
    'APPLICANT_VIEW',
    'APPLICANT_DOCUMENT_UPLOAD',

    'SKILL_VIEW',

    'VISA_VIEW',
  ],

  [ROLES.APPLICANT]: [
    'USER_SELF_REGISTER',

    'APPLICANT_SELF_VIEW',
    'APPLICANT_SELF_UPDATE',
    'APPLICANT_SELF_DOCUMENT_UPLOAD',
    'APPLICANT_SELF_STATUS_TRACK',

    'SKILL_VIEW',

    'JOB_VIEW',

    'APPLICATION_VIEW_SELF',
    'APPLICATION_CREATE_SELF',



    'VISA_VIEW_SELF',
  ],

  [ROLES.PARTNER_EMPLOYER]: [
    'EMPLOYER_SELF_REGISTER',
    'EMPLOYER_SELF_VIEW',
    'EMPLOYER_SELF_UPDATE',

    'VISA_VIEW',

    'JOB_CREATE',
    'JOB_UPDATE',
    'JOB_PUBLISH',
    'JOB_MANAGE',
    'JOB_VIEW',

    'MATCHING_VIEW',

    'APPLICATION_VIEW',
    'APPLICATION_MANAGE',

    'REPORT_VIEW'
  ],

  [ROLES.FINANCE_OFFICER]: [
    'APPLICANT_EXPENSE_TYPE_MANAGE',
    'APPLICANT_EXPENSE_MANAGE',
    'COMPANY_EXPENSE_TYPE_MANAGE',
    'COMPANY_EXPENSE_MANAGE'
  ]
} as const;
