export const NOTIFICATION_TYPES = {
  APPLICANT_SUBMITTED: 'APPLICANT_SUBMITTED',
  APPLICANT_VERIFIED: 'APPLICANT_VERIFIED',
  APPLICANT_REJECTED: 'APPLICANT_REJECTED',
  EMPLOYER_APPROVED: 'EMPLOYER_APPROVED',
  EMPLOYER_REJECTED: 'EMPLOYER_REJECTED',
  EMPLOYER_SUSPENDED: 'EMPLOYER_SUSPENDED',
  LOCAL_AGENCY_APPROVED: 'LOCAL_AGENCY_APPROVED',
  LOCAL_AGENCY_REJECTED: 'LOCAL_AGENCY_REJECTED',
  LOCAL_AGENCY_SUSPENDED: 'LOCAL_AGENCY_SUSPENDED',
  VISA_STATUS_CHANGE: 'VISA_STATUS_CHANGE',
  VISA_ATTEMPT_ISSUED: 'VISA_ATTEMPT_ISSUED',
  VISA_ATTEMPT_REJECTED: 'VISA_ATTEMPT_REJECTED',
  JOB_APPLICATION_RECEIVED: 'JOB_APPLICATION_RECEIVED',
  JOB_APPLICATION_STATUS_CHANGE: 'JOB_APPLICATION_STATUS_CHANGE',
  ACCOUNT_SETUP_REMINDER: 'ACCOUNT_SETUP_REMINDER',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  SYSTEM_ALERT: 'SYSTEM_ALERT',
} as const;

export type NotificationType =
  (typeof NOTIFICATION_TYPES)[keyof typeof NOTIFICATION_TYPES];
